### ISSUE TITLE
kontan.co.id

### ISSUE THREAD

**Issue by Pir8z** [reforget-id/AutoAllPage#1]
Gan, kalau bisa tolong tambahin kontan.co.id.
Contoh URL: 
https://lifestyle.kontan.co.id/news/5-universitas-dengan-jurusan-hukum-terbaik-di-indonesia-tahun-2021-versi-the-wur
https://personalfinance.kontan.co.id/news/apa-itu-gross-domestic-product-gdp-ini-penjelasan-lengkapnya
Thx.

**Comment by reforget-id** [comment]
Oke gan :+1:

**Comment by reforget-id** [comment]
Sudah gan.
Silahkan update ke versi 1.4.0
