### ISSUE TITLE
liputan6.com

### ISSUE THREAD

**Issue by 3xploiton3** [reforget-id/AutoAllPage#12]
**Request Website Baru**

**Contoh URL :**

https://www.liputan6.com/hot/read/5182486/wukuf-adalah-berdiam-diri-di-padang-arafah-ketahui-tata-caranya#:~:text=Wukuf%20dapat%20dimaknai%20sebagai%20berhentinya,sebagai%20inti%20dari%20ibadah%20haji.

**Keterangan :**

![image](https://github.com/reforget-id/AutoAllPage/assets/19517680/73ebe6a8-ab57-47c8-8f27-906e8fb0de15)

**Comment by reforget-id** [comment]
Itu harus diklik dulu baru muncul ?
Harusnya itu langsung otomatis muncul waktu scroll ke bawah tanpa harus diklik

**Comment by reforget-id** [comment]
Coba cek adblocknya, ada filternya AdBlockID yang ngeblok `liputan6.com##+js(aeld, scroll)`
Bisa di disable pakai filter ini `liputan6.com#@#+js(aeld, scroll)`
Harusnya udah normal kalo pakai itu.

**Comment by reforget-id** [comment]
https://github.com/realodix/AdBlockID/issues/1420
