### ISSUE TITLE
khazanah.republika.co.id

### ISSUE THREAD

**Issue by 3xploiton3** [reforget-id/AutoAllPage#14]
https://khazanah.republika.co.id/berita/ompfk3394/menakar-hukum-larangan-menshalati-jenazah-orang-munafik

![image](https://github.com/reforget-id/AutoAllPage/assets/19517680/8749c292-7376-402f-a14d-8e6dda627acb)

**Comment by reforget-id** [comment]
Update v2.2.1
Tolong dites

**Comment by 3xploiton3** [comment]
Nice Work 👍
