### ISSUE TITLE
merdeka.com

### ISSUE THREAD

**Issue by 3xploiton3** [reforget-id/AutoAllPage#15]
https://www.merdeka.com/jateng/6-ciri-ciri-orang-beriman-dalam-islam-perlu-diketahui-kln.html

![image](https://github.com/reforget-id/AutoAllPage/assets/19517680/a5293011-0fb0-4243-a0e7-a6f1b8c38cd9)

**Comment by reforget-id** [comment]
Sebelumnya, apa websitenya terasa berat ?
Karena itu yang saya alami waktu tes script

**Comment by 3xploiton3** [comment]
mungkin itu effect scroll yang memang dibikin begitu

**Comment by reforget-id** [comment]
Update v2.2.3
Silahkan dites dulu

**Comment by 3xploiton3** [comment]
gagal
![image](https://github.com/reforget-id/AutoAllPage/assets/19517680/275ac597-8b4f-4e71-9bec-e7b0784c3168)


seharusnya yang tampil
![image](https://github.com/reforget-id/AutoAllPage/assets/19517680/dcd36c73-836b-4ebe-b420-4b114da27737)

**Comment by reforget-id** [comment]
Cek update v2.2.4

**Comment by 3xploiton3** [comment]
berhasil,

terimakasih
