### ISSUE TITLE
papanskor.com

### ISSUE THREAD

**Issue by r3gamerz** [reforget-id/AutoAllPage#19]
**Request Website Baru**

**Contoh URL :**

https://www.papanskor.com/umpan-lambung/37312787546/mengapa-liga-conference-eropa-disebut-liga-melon-ternyata-begini-alasannya
https://www.papanskor.com/liga-champions/37313895906/klasemen-liga-champions-8-tim-ini-berpeluang-lolos-langsung-ke-babak-16-besar-ada-siapa-saja

**Keterangan :**

Tidak ada tombol "semua halaman"
Website menggunakan sistem -link'?page=2
bisa diredirect ke ?page=all

**Comment by reforget-id** [comment]
Sudah ditambah pada update v2.2.7 👍🏻

**Comment by r3gamerz** [comment]
thankyou
