### ISSUE TITLE
[Request] kompas.tv

### ISSUE THREAD

**Issue by chelseaislan** [reforget-id/AutoAllPage#8]
**Request a New Website**

**Contoh URL :**
https://www.kompas.tv/article/179500/gratis-masyarakat-umum-bisa-dapat-vaksin-covid-19-di-dki-jakarta-ini-link-pendaftarannya
https://www.kompas.tv/article/181403/diklaim-disusupi-geng-kriminal-qantas-bantah-dan-nyatakan-terganggu

**Keterangan :**
Can be bypassed with `?page=all`

**Comment by reforget-id** [comment]
Done v1.8.0 e2209d8

Maaf lama, banyak kesibukan hehe
