### ISSUE TITLE
Request untuk tidak melakukan url redirect

### ISSUE THREAD

**Issue by motfis** [reforget-id/AutoAllPage#9]
saya menggunakan script ini. sangat membantu untuk menghilangkan 'pagination' yang menggangu.
1 hal yang mungkin bisa ditingkatkan: saat ini jika kita men-klik link, pertama kali link tersebut akan dibuka, lalu akan di-redirect ke halaman penuh (page=all) nya (2 steps). jika kita menggunakan tombol back, redirect ini selalu aktif, membuat sulit untuk kembali ke halaman sebelumnya.

sebagai alternatif, apakah memungkinkan untuk menggunakan "onbeforerequest":
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest

jadi injeksi url dilakukan pada saat kita mengklik url, dan akan dialihkan langsung ke url dengan (page=all).

**Comment by reforget-id** [comment]
Makasih udah kasih saran

Yang saya tahu webrequest API hanya untuk extension dan tidak diekspos untuk userscript. Dan untuk saat ini hanya Tampermonkey yang mengimplementasikan GM.webrequest secara terbatas [Tampermonkey Issue 397](https://github.com/Tampermonkey/tampermonkey/issues/397#issuecomment-909169728). Saya sendiri belum tahu bagaimana behaviour dari GM.webrequest karena belum pernah coba. 

Untuk masalah ini saya bisa buat eventlistener disetiap url yang diklik user dan mengubah hrefnya sebelum url tersebut dibuka. Dan untuk url yang dicopy-paste tetap menggunakan cara lama. Tapi sebelum ini jadi, mungkin biasakan dulu untuk tekan tombol back 2 kali 😁

**Comment by reforget-id** [comment]
Update v1.9.0

Ternyata mudah, hanya mengganti `window.location.href`  menjadi  `window.location.replace('url')`. Sekarang, url yang mau diredirect tidak akan masuk ke history tombol back.
